// Generated by nitro
import type { Serialize, Simplify } from "nitropack/types";
declare module "nitropack/types" {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/api/download-test': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/download-test.get').default>>>>
    }
    '/api/ping': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/ping.get').default>>>>
    }
    '/api/upload-test': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/upload-test.post').default>>>>
    }
    '/__nuxt_error': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/.pnpm/@nuxt+nitro-server@3.21.2_db0@0.3.4_ioredis@5.11.0_magicast@0.5.3_nuxt@3.21.2_@emnapi+c_fa24b47cbe8cccb5fa4be77c380c6ab5/node_modules/@nuxt/nitro-server/dist/runtime/handlers/renderer').default>>>>
    }
    '/__nuxt_island/**': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/#internal/nuxt/island-renderer').default>>>>
    }
  }
}
export {}