// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 8/10/2026, 9:58:31 PM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.ts";
const config = [
{"content":{"files":["/Users/ousa/Desktop/Nuxt_3/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/ousa/Desktop/Nuxt_3/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/ousa/Desktop/Nuxt_3/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/ousa/Desktop/Nuxt_3/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/ousa/Desktop/Nuxt_3/plugins/**/*.{js,ts,mjs}","/Users/ousa/Desktop/Nuxt_3/composables/**/*.{js,ts,mjs}","/Users/ousa/Desktop/Nuxt_3/utils/**/*.{js,ts,mjs}","/Users/ousa/Desktop/Nuxt_3/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/ousa/Desktop/Nuxt_3/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/ousa/Desktop/Nuxt_3/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/ousa/Desktop/Nuxt_3/app.config.{js,ts,mjs}","/Users/ousa/Desktop/Nuxt_3/app/spa-loading-template.html"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;